/* eslint-disable react-hooks/exhaustive-deps */
import Head from "next/head";
import styles from "@/styles/Home.module.css";
import Navbar from "../../components/Navbar";
import HomeRegister from "../../components/HomeRegister";
import Line from "../../ui/Line";
import HomeApps from "../../components/HomeApps";
import HomeContest from "../../components/HomeContest";
import HomeFAQ from "../../components/HomeFAQ";
import HomeFooter from "../../components/HomeFooter";
import useMountTransition from "../../hooks/useMountTransition";
import MenuIcon from "@mui/icons-material/Menu";
import { useCallback, useState } from "react";
import theme from "../../theme/theme";
import Sidebar from "../../components/Sidebar";
import { useMemo } from "react";
import { IconButton } from "@mui/material";

export default function Home() {
  const [sidebar, setSidebar] = useState(false);
  const hasTransitionedIn = useMountTransition(sidebar, 500);

  const openSidebar = useCallback(() => {
    setSidebar(true);
  }, [sidebar]);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main style={{ position: "relative" }}>
        {!sidebar && (
          <IconButton
            sx={{
              position: "fixed",
              top: "1rem",
              right: "1rem",
              zIndex: "1",
              width: "3rem",
              backgroundColor: "rgba(0,0,0,0.4)",
              display: { xs: "block", md: "none" },
            }}
            onClick={() => openSidebar()}
          >
            <MenuIcon
              sx={{
                color: theme.palette.text.light,
                "&:hover": {
                  color: theme.palette.secondary.light,
                },
              }}
            />
          </IconButton>
        )}

        {(hasTransitionedIn || sidebar) && (
          <Sidebar
            sidebar={sidebar}
            setSidebar={setSidebar}
            hasTransitionedIn={hasTransitionedIn}
          />
        )}
        <Navbar />
        <Line />
        <HomeRegister />
        <HomeApps />
        <HomeContest />
        <HomeFAQ />
        <HomeFooter />
      </main>
    </>
  );
}
